### ISSUE TITLE
Why do we have svelte as our non-dev dependency?

### ISSUE THREAD

**Issue by NERDYLIZARD** [kolodziejczak-sz/svelte-redux-connect#10]
I'm looking for a tool to help me integrate Svelte with Redux. Currently, this project is, by far, answer all the needs. Moreover, it's easy to adopt coming for using Redux with React. When I look up the package in [bundlephobia.com](bundlephobia.com) though, I can't help but notice 86% of it is svelte. Should we have them as a peer-dependency since the sole purpose of our project is to be used alongside Svelte?

**Comment by kolodziejczak-sz** [comment]
sorry for the late reply, you're absolutely right, I'm gonna fix this issue today

**Comment by snkj5** [comment]
the svelte-redux-connect@1.2.1 includes `svelte` as peerDependency. Thank you for you issue

![obraz](https://user-images.githubusercontent.com/16175875/124779450-14849180-df42-11eb-9ba6-3dd2deb15e56.png)
